name: Linux CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 6 * * 6'
jobs:
  build-ubuntu:
    strategy:
      fail-fast: false
      matrix:
        include:
          - {os: ubuntu-latest, crystal: latest}
          - {os: ubuntu-latest, crystal: nightly}  
    runs-on: ${{matrix.os}}
    container:
      image: crystallang/crystal
    steps:
    - uses: actions/checkout@v2
    - name: apt update?
      run: apt-get update
    - name: Install dependencies
      run: apt-get install -y libnlopt0
    - name: create link to NLOpt
      run: ln -s /usr/lib/x86_64-linux-gnu/libnlopt.so.0 /usr/lib/x86_64-linux-gnu/libnlopt.so
    - name: Run tests
      run: crystal spec
